// <auto-generated />
namespace EFConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class V2_TypeAdd_Customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V2_TypeAdd_Customers));
        
        string IMigrationMetadata.Id
        {
            get { return "202108010803228_V2_TypeAdd_Customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
